# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-0d6756b9-fe6b-4cdd-89d3-c788ee331981";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0d6756b9-fe6b-4cdd-89d3-c788ee331981".device =
    "/dev/disk/by-uuid/0d6756b9-fe6b-4cdd-89d3-c788ee331981";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AACE-CFF8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-8e40e0e9-9ca3-442d-87e1-360d27a4c569"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
